apiVersion: v1
kind: Service
metadata:
  name: tonic-queue
  labels:
    app: tonic-queue
spec:
  ports:
  - port: 25672
    targetPort: 15672
  selector:
    app: tonic-queue
status:
  loadBalancer: {}
