apiVersion: v1
kind: Service
metadata:
  name: tonic-web-server
  namespace: tonic
  labels:
    app: tonic-web-server
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: "https"
    port: 443
    targetPort: 443
    nodePort: 30443
  type: LoadBalancer
  selector:
    app: tonic-web-server
status:
  loadBalancer: {}
