apiVersion: apps/v1
kind: Deployment
metadata:
  name: tonic-pii-detection
  namespace: tonic
  labels:
    app: tonic-pii-detection  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tonic-pii-detection
  strategy: {}
  template:
    metadata:
      labels:
        app: tonic-pii-detection
    spec:
      containers:
      - image: {{ .Values.dockerRepoBaseUrl }}/tonic_pii_detection:latest
        imagePullPolicy: ""
        name: tonic-pii-detection
        ports:
        - containerPort: 7687
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
