apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tonic-web-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: tonic-web-server
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.nginxBodySize }}
spec:
  ingressClassName: nginx-production-private
  tls:
    - hosts:
        - tonic.internal.capsule.com
      secretName: tonic-web-server-tls
  rules:
    - host: tonic.internal.capsule.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: tonic-web-server
                port:
                  name: http
