{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: tonic-worker
  name: tonic-worker-serviceaccount
  namespace: {{ .Release.Namespace }}
{{- end }}
