apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tonic-web-server
  name: tonic-web-server
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tonic-web-server
  strategy: {}
  template:
    metadata:
      labels:
        app: tonic-web-server
    spec:
      containers:
      - env:
        - name: TONIC_DB_DATABASE
          value: {{ .Values.tonicdb.dbname }}
        - name: TONIC_DB_USERNAME
          value: {{ .Values.tonicdb.user }}
        - name: TONIC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tonic-db-password
              key: password
        - name: TONIC_DB_PORT
          value: {{quote .Values.tonicdb.port }}
        - name: TONIC_DB_SSLMODE
          value: {{ .Values.tonicdb.sslMode }}
        - name: TONIC_DB_HOST
          value: {{ .Values.tonicdb.host }}
          {{- if .Values.tonicStatisticsSeed }}
        - name: TONIC_STATISTICS_SEED
          value: {{quote .Values.tonicStatisticsSeed }}
          {{- end }}
        - name: ENABLE_LOG_COLLECTION
          value: {{quote .Values.enableLogCollection }}
        - name: ENVIRONMENT_NAME
          value: {{ .Values.environmentName }}
          {{- if .Values.tonicLicense }}
        - name: TONIC_LICENSE
          value: {{quote .Values.tonicLicense }}
          {{- end }}
        image: quay.io/tonicai/tonic_web_server:{{ .Values.tonicVersion }}
        imagePullPolicy: ""
        name: tonic-web-server
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
      serviceAccountName: ""
      imagePullSecrets:
      - name: tonicai-build-writer-pull-secret
      volumes: null
status: {}
