apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tonic-web-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: tonic-web-server
  annotations:
    kubernetes.io/ingress.class: nginx-production-private
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.nginxBodySize }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.nginxConnectTimeout }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.nginxSendTimeout}}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.nginxReadTimeout }}
spec:
  tls:
    - hosts:
        - tonic.internal.capsule.com
      secretName: tonic-web-server-tls
  rules:
    - host: tonic.internal.capsule.com
      http:
        paths:
          - path: /
            backend:
              serviceName: tonic-web-server
              servicePort: http
